using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FourzyGameModel.Model
{
    public enum PatternType
    {
        FullDots,
        BlockEdge,
        BlockAllEdges,
        BubbleEdge,
        LargeCircle,  //A circle one space from edge
        FullCheckers,
        AlmostFullCheckers,
        DiagonalLines,
        Dots,
        DottedCross,
        DottedLine,
        OneFullLine,
        FullLines,
        HorizontalLine,
        VerticalLine,
        DoubleLine,
        DoubleRow,
        PinWheel,
        FillGaps,
        CrossTheBoard,
        FullStarPattern,
        BubbleEdgeRight,
        BubbleEdgeLeft,
        BubbleEdgeUp,
        BubbleEdgeDown,
        Corners,
        CentralCorners,
        Four,
        CenterFour,
        ACouple,
        OneRandom,
        TwoRandom,
        ThreeRandom,
        CenterSixteen,
        LargeCheckers,
        WideLine,
        WideCross,
        DoubleCross,
        SmallPinWheel,
        PartialBlockEdges,
        BlockEdgesOneSpace,
        BlockEdgesTwoSpace,
        RandomBlockEdges,
        SmallSymmetricBlockEdgePattern,
        MediumSymmetricBlockEdgePattern,
        LargeSymmetricBlockEdgePattern,
        CenterBlob,
        OuterRing,
        CenterRing,
        CrossQuads,
        OuterCorners,
        CenterDiagonal,
        EdgeBump,
        EdgeBumpDuo,
        EdgeSpike,
        EdgeSpikeDuo,
        EdgeBumpQuartet,
        EdgeSpikeQuartet,
        Half,
        Full,
        AlmostFull,
        CrossBoardOneTurn,
        CrossBoardTwoTurnPattern,
        CrossBoardFourTurnPattern,
        CenterOne,
        CenterLineOfFour,
        TwoCenterLinesOfFour,
        ThreeCenterLinesOfFour,
        OneRandomRingOne,
        OneRandomRingTwo,
        OneRandomRingThree,
        TwoRandomRingOne,
        TwoRandomRingTwo,
        TwoRandomRingThree,
        FourRandomRingOne,
        FourRandomRingTwo,
        FourConnectedRingOne,
        FourConnectedRingTwo,
        TwoSymmetricRingOne,
        TwoSymmetricRingTwo,
        TwoSymmetricRingThree,
        FourSymmetricRingOne,
        FourSymmetricRingTwo,
        AlternateRingOne,
        AlternateRingTwo
    }

    public enum RelativeDirection { IN, OUT, NONE}
    public enum LineFillStyle { RANDOM, CONNECTED, SYMMETRIC, FILLED, ALTERNATING }

}
