namespace FourzyGameModel.Model
{
    public enum SpellId { HEX,
                        HOLD_FOURZY,
                        PRISON,
                        DARKNESS,
                        CREEPING_DARKNESS,
                        MISDIRECTION,
                        FRUIT,
                        SLURP,
                        SQUIRT_WATER,
                        ROTATE,
                        ROTATE_EVERYTHING,
                        THROW_BOMB,
                        PLACE_LURE,
                        ICE_WALL,
                        FIRE_WALL,
                        DIG,
                        GROWL,
                        SUMMON_SPECTER,
                        AWAKEN,
                        NUDGE_SPIRIT,
                        BITE,
                        RAINBOW,
                        PUNCH,
                        ABSORB_SPIRIT,
                        PASSTHROUGH,
                        UNDO,
                        TIME,
                        RAIN,
                        SNOW,
                        SUN,
                        MOVE_GHOST,
                        FREEZE,
                        MELT,
                        LIFE,
                        DEATH};
    public enum SpellType { MOVE, ASYNC};
    public enum SpellFailureType { FIZZLE, LOCATION, NOT_ENOUGH_MAGIC};
}
